id: f65aee8dc5b94b7fae52bc356f49c337
initial_creation_type: ocr
source_metadata:
  volumes:
    99ff0738b26445da99a04b3bfafae475:
      base_file: v057.txt
      image_group_id: I1PD95902
      title: ཐེག་པ་ཆེན་པོ་ཉི་ཤུ་པ།
      total_pages: 1605
      volume_number: 57
