id: f65aee8dc5b94b7fae52bc356f49c337
initial_creation_type: ocr
source_metadata:
  volumes:
    f7f108fee8df4e97a43a3137e86bb30c:
      base_file: v026.txt
      image_group_id: I1PD95871
      title: ''
      total_pages: 1902
      volume_number: 26
